#!/usr/bin/env python3
#
# Gracemont Industrial Control Framework - ARM64 RTOS
# Copyright (C) 2024 Zixiao System <https://github.com/Zixiao-System>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Configuration Header Generator
# Converts .config to C header file
#

import sys
import os
import re
from datetime import datetime

def parse_config(config_file):
    """Parse .config file and return dictionary of config values."""
    config = {}

    with open(config_file, 'r') as f:
        for line in f:
            line = line.strip()

            # Skip comments and empty lines
            if not line or line.startswith('#'):
                # Check for "is not set" comments
                match = re.match(r'^#\s*(CONFIG_\w+)\s+is not set', line)
                if match:
                    config[match.group(1)] = None
                continue

            # Parse key=value
            match = re.match(r'^(CONFIG_\w+)=(.+)$', line)
            if match:
                key = match.group(1)
                value = match.group(2)

                # Handle different value types
                if value == 'y':
                    config[key] = True
                elif value == 'n':
                    config[key] = False
                elif value.startswith('"') and value.endswith('"'):
                    config[key] = value[1:-1]  # String
                elif value.startswith('0x'):
                    config[key] = value  # Hex
                else:
                    try:
                        config[key] = int(value)  # Integer
                    except ValueError:
                        config[key] = value  # Keep as string

    return config

def generate_header(config, output_file):
    """Generate C header file from config dictionary."""

    header = f'''/*
 * Gracemont Industrial Control Framework - ARM64 RTOS
 * Copyright (C) 2024 Zixiao System <https://github.com/Zixiao-System>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/genconfig.py
 * Generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 *
 * To modify configuration, run: make menuconfig
 */

#ifndef AUTOCONF_H
#define AUTOCONF_H

'''

    # Group configurations by prefix
    groups = {
        'System': [],
        'Memory': [],
        'Kernel': [],
        'ARM64': [],
        'UART': [],
        'ETH': [],
        'Timer': [],
        'NET': [],
        'TCP': [],
        'UDP': [],
        'Modbus': [],
        'OPC UA': [],
        'PROFINET': [],
        'Debug': [],
        'Other': []
    }

    group_prefixes = {
        'CPU_FREQ': 'System',
        'TICK_RATE': 'System',
        'MAX_TASKS': 'System',
        'MAX_PRIORITY': 'System',
        'TASK_STACK': 'System',
        'IDLE_STACK': 'System',
        'HEAP': 'Memory',
        'DMA_POOL': 'Memory',
        'ZBUF': 'Memory',
        'KERNEL': 'Kernel',
        'ARM64': 'ARM64',
        'GIC': 'ARM64',
        'MMU': 'ARM64',
        'DCACHE': 'ARM64',
        'ICACHE': 'ARM64',
        'UART': 'UART',
        'ETH': 'ETH',
        'TIMER': 'Timer',
        'NET': 'NET',
        'TCP': 'TCP',
        'UDP': 'UDP',
        'MODBUS': 'Modbus',
        'OPCUA': 'OPC UA',
        'PROFINET': 'PROFINET',
        'DEBUG': 'Debug',
        'BUILD_TESTS': 'Debug',
    }

    for key, value in sorted(config.items()):
        if value is None:
            continue  # Skip "not set" options

        # Determine group
        name = key.replace('CONFIG_', '')
        group = 'Other'
        for prefix, grp in group_prefixes.items():
            if name.startswith(prefix):
                group = grp
                break

        groups[group].append((key, value))

    # Generate defines
    for group_name, items in groups.items():
        if not items:
            continue

        header += f'/* {group_name} Configuration */\n'

        for key, value in items:
            if value is True:
                header += f'#define {key} 1\n'
            elif value is False:
                header += f'/* #undef {key} */\n'
            elif isinstance(value, int):
                header += f'#define {key} {value}\n'
            elif isinstance(value, str):
                if value.startswith('0x'):
                    header += f'#define {key} {value}\n'
                else:
                    header += f'#define {key} "{value}"\n'

        header += '\n'

    header += '#endif /* AUTOCONF_H */\n'

    # Write output file
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(header)

    print(f'Generated: {output_file}')

def main():
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <.config> <output.h>')
        sys.exit(1)

    config_file = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.exists(config_file):
        print(f'Error: Config file not found: {config_file}')
        sys.exit(1)

    config = parse_config(config_file)
    generate_header(config, output_file)

if __name__ == '__main__':
    main()
